imageName: kaizentm/gitops-connector
imageTag: $IMAGE_TAG
containerPort: 8080

gitRepositoryType: $GIT_REPOSITORY_TYPE
ciCdOrchestratorType: $CICD_ORCHESTRATOR_TYPE
gitOpsOperatorType: $GITOPS_OPERATOR_TYPE
gitOpsAppURL: $GITOPS_APP_URL
azdoGitOpsRepoName: $AZDO_GITOPS_REPO_NAME
azdoPrRepoName: $AZDO_PR_REPO_NAME
azdoOrgUrl: $AZDO_ORG_URL
orchestratorPAT: $ORCHESTRATOR_PAT

gitHubGitOpsRepoName: $GITHUB_GITOPS_REPO_NAME
gitHubGitOpsManifestsRepoName: $GITHUB_GITOPS_MANIFEST_REPO_NAME
gitHubOrgUrl: $GITHUB_ORG_URL

# Optional list of subscriber endpoints to send raw JSON to
#subscribers:
#  sub1: http://localhost:8080/gitopsphase
#  sub2: http://127.0.0.1:1234/
