apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: gitops-connector
  namespace: flux-system
spec:
  url: https://azure.github.io/gitops-connector/
  interval: 1m
---  
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: gitops-connector
  namespace: flux-system
spec:
  chart:
    spec:
      chart: gitops-connector
      version: ">=1.x.x-0"
      sourceRef:
        kind: HelmRepository
        name: gitops-connector
        namespace: flux-system
      interval: 2m        
  interval: 1m
  values:
    gitRepositoryType: GITHUB          
    ciCdOrchestratorType: GITHUB
    gitOpsOperatorType: FLUX
    gitHubGitOpsRepoName: gitops-connector
    gitHubGitOpsManifestsRepoName: gitops-manifests
    gitHubOrgUrl: https://api.github.com/repos/kaizentm
    gitOpsAppURL: https://github.com/kaizentm/gitops-manifests/commit
    orchestratorPAT: 
