---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: gitops-connector-dev
  namespace: flux-system
spec:
  interval: 30s
  ref:
    branch: dev
  timeout: 20s
  url: https://github.com/kaizentm/gitops-manifests
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: gitops-connector-dev
  namespace: flux-system
spec:
  targetNamespace: dev
  interval: 0m10s
  path: ./gitops-connector/manifest
  prune: false
  # healthChecks: 
  #   - kind: Deployment
  #     name: gitops-connector
  #     namespace: dev
  sourceRef:
    kind: GitRepository
    name: gitops-connector-dev

