apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "gitops-connector.fullname" . }}
  labels: {{- include "gitops-connector.labels" . | nindent 4 }}
data:
  GIT_REPOSITORY_TYPE: {{ required "Provide a value for gitRepositoryType" .Values.gitRepositoryType}}
  CICD_ORCHESTRATOR_TYPE: {{ required "Provide a value for ciCdOrchestratorType" .Values.ciCdOrchestratorType}}
  GITOPS_OPERATOR_TYPE: {{ required "Provide a value for gitOpsOperatorType" .Values.gitOpsOperatorType}}
  GITOPS_APP_URL: {{ required "Provide a value for gitOpsAppURL" .Values.gitOpsAppURL}}

  {{- if eq .Values.gitRepositoryType "AZDO"}}
  AZDO_GITOPS_REPO_NAME: {{ required "Provide a value for azdoGitOpsRepoName" .Values.azdoGitOpsRepoName}}
  {{- end }}

  {{- if and (eq .Values.ciCdOrchestratorType "AZDO") (.Values.azdoPrRepoName)}}
  AZDO_PR_REPO_NAME: {{ .Values.azdoPrRepoName}}
  {{- end }}

  {{- if or (eq .Values.gitRepositoryType "AZDO") (eq .Values.ciCdOrchestratorType "AZDO")}}
  AZDO_ORG_URL: {{ required "Provide a value for azdoOrgUrl" .Values.azdoOrgUrl}}
  {{- end }}

  {{- if eq .Values.ciCdOrchestratorType "GITHUB"}}
  GITHUB_GITOPS_REPO_NAME: {{ required "Provide a value for gitHubGitOpsRepoName" .Values.gitHubGitOpsRepoName}}
  {{- end }}

  {{- if eq .Values.gitRepositoryType "GITHUB"}}
  GITHUB_GITOPS_MANIFEST_REPO_NAME: {{ required "Provide a value for gitHubGitOpsManifestsRepoName" .Values.gitHubGitOpsManifestsRepoName}}
  {{- end }}

  {{- if or (eq .Values.gitRepositoryType "GITHUB") (eq .Values.ciCdOrchestratorType "GITHUB")}}
  GITHUB_ORG_URL: {{ required "Provide a value for gitHubOrgUrl" .Values.gitHubOrgUrl}}
  {{- end }}
