{{- if .Values.orchestratorPAT -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gitops-connector.fullname" . }}
  labels: {{- include "gitops-connector.labels" . | nindent 4 }}
stringData:
  PAT: {{ .Values.orchestratorPAT }}
type: Opaque
{{- end }}